import { siteUrl } from "@/lib/seoSchema";

export { siteUrl };

export const indexableRoutes = [
  "/",
  "/about",
  "/accessible-smokies",
  "/advertise",
  "/affiliate-disclosure",
  "/best-time-to-visit",
  "/business-listings",
  "/business-listings/claim",
  "/cades-cove",
  "/contact",
  "/corrections",
  "/deals",
  "/disclaimer",
  "/do",
  "/dollywood-day-plan",
  "/eat",
  "/eat/family-friendly",
  "/eat-stay-shop",
  "/editorial-policy",
  "/events",
  "/explore",
  "/first-time-smokies",
  "/free-and-cheap-smokies",
  "/gatlinburg",
  "/gatlinburg-vs-pigeon-forge",
  "/gatlinburg-without-walking-too-much",
  "/go",
  "/go/parking",
  "/hiking",
  "/how-many-days",
  "/parking-tag",
  "/pigeon-forge",
  "/pigeon-forge-with-kids",
  "/privacy",
  "/rainy-day",
  "/rainy-day-smokies-with-kids",
  "/restaurants",
  "/restaurants/gatlinburg",
  "/restaurants/pigeon-forge",
  "/scenic-drives",
  "/see",
  "/sevierville",
  "/smokies-parking-trolley-guide",
  "/smokies-with-toddlers",
  "/source-and-verification-policy",
  "/sponsored-content-policy",
  "/start-here",
  "/start-planning",
  "/stay",
  "/stay/cabins",
  "/terms",
  "/the-track-pigeon-forge-closing",
  "/things-to-do",
  "/things-to-do/gatlinburg",
  "/things-to-do/pigeon-forge",
  "/townsend",
  "/visitor-resources",
  "/what-to-skip",
  "/where-to-stay",
  "/where-to-stay-in-the-smokies-by-trip-type",
] as const;
