import type { GuidePageData, LinkItem, TimelineItem } from "@/components/guide";

export const guideLinks: LinkItem[] = [
  { title: "Plan Your Smokies Trip", href: "/plan-your-trip", description: "Answer a few questions and get a practical starter plan." },
  { title: "Where to Stay", href: "/where-to-stay", description: "Choose the right base town before choosing attractions." },
  { title: "Gatlinburg vs Pigeon Forge", href: "/gatlinburg-vs-pigeon-forge", description: "Pick the better town for your group and trip style." },
  { title: "How Many Days", href: "/how-many-days", description: "Choose a realistic trip length without cramming the map." },
  { title: "Rainy Day", href: "/rainy-day", description: "Build a wet-weather day without driving all over the county." },
  { title: "Cades Cove", href: "/cades-cove", description: "Plan the loop like a real outing, not a quick add-on." },
  { title: "Parking Tag", href: "/parking-tag", description: "Know what to verify before you park in the national park." },
  { title: "First Time Smokies", href: "/first-time-smokies", description: "A simple first-trip shape for families and mixed groups." },
  { title: "Scenic Drives", href: "/scenic-drives", description: "Choose drives by crowd risk, walking load and base town." },
  { title: "Things To Do", href: "/things-to-do", description: "Match activities to kids, rain, budget, scenery and pace." },
  { title: "Restaurants", href: "/restaurants", description: "Pick meals by route and situation, not just ratings." },
  { title: "Deals", href: "/deals", description: "Use savings only when they fit the trip." },
];

export const highIntentRouteLinks = guideLinks;

export const towns = [
  {
    name: "Gatlinburg",
    href: "/gatlinburg",
    bestFor: "Walkability, first-timers, park access, downtown attractions and people who want to park once.",
    skipIf: "You hate crowds, parking stress or tight downtown streets.",
    mistake: "Trying to drive between every stop instead of parking once and walking or using trolley options.",
    links: [
      { title: "Gatlinburg guide", href: "/gatlinburg" },
      { title: "Gatlinburg vs Pigeon Forge", href: "/gatlinburg-vs-pigeon-forge" },
      { title: "Restaurants Gatlinburg", href: "/restaurants/gatlinburg" },
      { title: "Things to do Gatlinburg", href: "/things-to-do/gatlinburg" },
      { title: "Parking and trolley", href: "/smokies-parking-trolley-guide" },
    ],
  },
  {
    name: "Pigeon Forge",
    href: "/pigeon-forge",
    bestFor: "Families, Dollywood, dinner shows, attractions and easier parking compared with Gatlinburg.",
    skipIf: "You want a quiet mountain town or expect to walk everywhere.",
    mistake: "Stacking the whole Parkway into one day.",
    links: [
      { title: "Pigeon Forge guide", href: "/pigeon-forge" },
      { title: "Pigeon Forge with kids", href: "/pigeon-forge-with-kids" },
      { title: "Rainy day", href: "/rainy-day" },
      { title: "Things to do Pigeon Forge", href: "/things-to-do/pigeon-forge" },
      { title: "Restaurants Pigeon Forge", href: "/restaurants/pigeon-forge" },
    ],
  },
  {
    name: "Sevierville",
    href: "/sevierville",
    bestFor: "Value lodging, outlets, gateway access and visitors who do not need to sleep in the center of the tourist strip.",
    skipIf: "You want to walk out your door into the park or downtown Gatlinburg.",
    mistake: "Assuming Sevierville is only a pass-through.",
    links: [
      { title: "Sevierville guide", href: "/sevierville" },
      { title: "Where to stay", href: "/where-to-stay" },
      { title: "Restaurants", href: "/restaurants" },
    ],
  },
  {
    name: "Townsend",
    href: "/townsend",
    bestFor: "Quiet trips, Cades Cove, scenic drives, slower pace, couples and crowd-avoiders.",
    skipIf: "You want nightlife, heavy attractions or constant entertainment.",
    mistake: "Expecting Pigeon Forge energy on the quiet side.",
    links: [
      { title: "Townsend guide", href: "/townsend" },
      { title: "Cades Cove", href: "/cades-cove" },
      { title: "Scenic drives", href: "/scenic-drives" },
    ],
  },
  {
    name: "Wears Valley",
    href: "/where-to-stay",
    bestFor: "Cabins, views, Foothills Parkway access and a slower base between Townsend and Pigeon Forge.",
    skipIf: "You need walkability or quick access to every attraction.",
    mistake: "Booking for the view without checking the route your group will drive each day.",
    links: [
      { title: "Where to stay", href: "/where-to-stay" },
      { title: "Scenic drives", href: "/scenic-drives" },
      { title: "Plan your trip", href: "/plan-your-trip" },
    ],
  },
  {
    name: "Cherokee / Bryson City",
    href: "/where-to-stay",
    bestFor: "NC-side park access, elk, Deep Creek, railroad-style trips and travelers who want a different Smokies route.",
    skipIf: "Your whole trip is centered on Dollywood, Pigeon Forge or Gatlinburg.",
    mistake: "Treating the NC side as a quick add-on to a TN-heavy attraction trip.",
    links: [
      { title: "Where to stay", href: "/where-to-stay" },
      { title: "Scenic drives", href: "/scenic-drives" },
      { title: "Accessible Smokies", href: "/accessible-smokies" },
    ],
  },
];

export const plannerOptions = {
  base: ["Gatlinburg", "Pigeon Forge", "Sevierville", "Townsend / Wears Valley", "Not sure yet", "NC side / Cherokee / Bryson City"],
  time: ["One day", "Two days", "Three days", "Four or more days", "Just an evening"],
  group: ["Adults only", "Family with young kids", "Family with teens", "Grandparents / seniors", "Mobility-limited group", "Mixed group"],
  day: ["Park and scenery", "Attractions", "Rainy day", "Low budget", "Low crowds", "Food and shopping", "Dollywood day", "Cades Cove day"],
  risk: ["Traffic", "Too much walking", "Rain", "Overspending", "Bored kids", "Full parking lots", "Mountain roads", "Long lines"],
};

export type PlannerTemplate = {
  id: string;
  title: string;
  match: string[];
  base: string;
  firstStop: string;
  mainPlan: TimelineItem[];
  freeAlternative: string;
  paidOption: string;
  foodPairing: string;
  parkingWarning: string;
  crowdWarning: string;
  rainBackup: string;
  skip: string;
  links: LinkItem[];
};

const commonPlanLinks = [
  { title: "Where to stay", href: "/where-to-stay", description: "Match your base town to your actual days." },
  { title: "Rainy day", href: "/rainy-day", description: "Keep a backup that does not wreck the route." },
  { title: "What to skip", href: "/what-to-skip", description: "Avoid the common time traps." },
];

export const plannerResultTemplates: PlannerTemplate[] = [
  {
    id: "family-pigeon-forge",
    title: "First-time family with a Pigeon Forge base",
    match: ["Pigeon Forge", "Family with young kids", "Family with teens", "Attractions"],
    base: "Pigeon Forge",
    firstStop: "One Parkway anchor your group actually wants.",
    mainPlan: [
      { label: "Morning", text: "Choose one family anchor before adding smaller stops." },
      { label: "Lunch", text: "Eat near the same corridor so the day does not turn into traffic practice." },
      { label: "Afternoon", text: "Add one lighter attraction or reset at your lodging." },
      { label: "Evening", text: "Use dinner or a show category if the group still has energy." },
    ],
    freeAlternative: "A scenic drive, river stop or visitor center-style pause instead of another paid ticket.",
    paidOption: "Attraction, show or theme-park category.",
    foodPairing: "Family-friendly Parkway meal near the attraction cluster.",
    parkingWarning: "Do not assume every stop is easy just because it is on the Parkway.",
    crowdWarning: "Long lines and traffic stack up when you chase too many stops.",
    rainBackup: "Swap to an indoor attraction category and keep dinner nearby.",
    skip: "Skip crossing into Gatlinburg for one small add-on.",
    links: commonPlanLinks,
  },
  {
    id: "rainy-family",
    title: "Rainy-day family plan from Pigeon Forge or Gatlinburg",
    match: ["Rainy day", "Rain", "Family with young kids", "Pigeon Forge", "Gatlinburg"],
    base: "Pigeon Forge or Gatlinburg",
    firstStop: "One indoor anchor, not a county-wide list.",
    mainPlan: [
      { label: "Morning", text: "Pick the indoor stop closest to your lodging or first meal." },
      { label: "Lunch", text: "Use a meal as the reset instead of adding another drive." },
      { label: "Afternoon", text: "Watch the weather window and keep one short outdoor option ready." },
      { label: "Evening", text: "Choose dinner, a show category or a quiet lodging reset." },
    ],
    freeAlternative: "Covered shopping, a visitor center, scenic pull-offs when showers pass or a slow food-focused day.",
    paidOption: "Indoor attraction, aquarium, arcade, museum or dinner-show category.",
    foodPairing: "Pick food near the indoor anchor, not across town.",
    parkingWarning: "Rain makes short drives feel longer around busy corridors.",
    crowdWarning: "Indoor spots can fill when everyone changes plans at once.",
    rainBackup: "This is the rain backup; keep one outdoor swap if showers break.",
    skip: "Skip trying to rescue every outdoor plan in the same day.",
    links: [
      { title: "Rainy day guide", href: "/rainy-day", description: "Build the day by town." },
      { title: "Pigeon Forge things to do", href: "/things-to-do/pigeon-forge", description: "Indoor and family categories." },
      { title: "Gatlinburg things to do", href: "/things-to-do/gatlinburg", description: "Walkable and indoor categories." },
    ],
  },
  {
    id: "low-crowd-townsend",
    title: "Low-crowd scenic plan from Townsend or Wears Valley",
    match: ["Townsend / Wears Valley", "Low crowds", "Park and scenery", "Traffic", "Mountain roads"],
    base: "Townsend or Wears Valley",
    firstStop: "A scenic drive or quiet-side park stop.",
    mainPlan: [
      { label: "Morning", text: "Start with scenery before the loop roads and overlooks get busier." },
      { label: "Lunch", text: "Keep lunch simple on the quiet side or near the route back." },
      { label: "Afternoon", text: "Add Foothills Parkway, a visitor center or a short overlook stop." },
      { label: "Evening", text: "Return before you are tempted into a late cross-county drive." },
    ],
    freeAlternative: "Foothills Parkway, overlooks and quiet-side scenic stops.",
    paidOption: "Guided tour category only if verified and clearly labeled later.",
    foodPairing: "Quiet-side meal or simple picnic-style stop.",
    parkingWarning: "Scenic does not mean parking-free. Verify road conditions before you go.",
    crowdWarning: "Cades Cove and popular overlooks still draw crowds.",
    rainBackup: "Move to a town meal, visitor center or lower-driving day.",
    skip: "Skip forcing Pigeon Forge entertainment into this calm day.",
    links: [
      { title: "Cades Cove", href: "/cades-cove", description: "Plan the loop with time." },
      { title: "Scenic drives", href: "/scenic-drives", description: "Choose the right road." },
      { title: "Accessible Smokies", href: "/accessible-smokies", description: "Low-walking ideas with caution." },
    ],
  },
  {
    id: "cades-cove",
    title: "Cades Cove day",
    match: ["Cades Cove day", "Townsend / Wears Valley", "Park and scenery"],
    base: "Townsend, Wears Valley or a trip willing to give the loop real time.",
    firstStop: "Cades Cove after checking current park conditions.",
    mainPlan: [
      { label: "Morning", text: "Go early if you want a calmer loop and better patience from the group." },
      { label: "Lunch", text: "Plan food before or after the loop rather than during a rushed detour." },
      { label: "Afternoon", text: "Pair with Townsend or a simple scenic stop, not a packed attraction list." },
      { label: "Evening", text: "Keep the evening easy after a slow park day." },
    ],
    freeAlternative: "Townsend-side scenic stops and pull-offs.",
    paidOption: "None needed for the core day.",
    foodPairing: "Townsend or Wears Valley before or after the loop.",
    parkingWarning: "Parking and pull-offs can be limited. Details can change.",
    crowdWarning: "The loop is slow by design and slower when traffic stacks.",
    rainBackup: "Use Townsend, a visitor center or a town meal if weather makes the loop unpleasant.",
    skip: "Skip Cades Cove as a quick add-on between busy town plans.",
    links: [
      { title: "Cades Cove guide", href: "/cades-cove", description: "What to know before the loop." },
      { title: "Townsend", href: "/townsend", description: "Quiet-side base logic." },
      { title: "What to skip", href: "/what-to-skip", description: "Avoid the rushing mistake." },
    ],
  },
  {
    id: "gatlinburg-walkable",
    title: "Gatlinburg walkable day",
    match: ["Gatlinburg", "Food and shopping", "Too much walking"],
    base: "Gatlinburg",
    firstStop: "Park once, then walk the downtown plan in a sensible order.",
    mainPlan: [
      { label: "Morning", text: "Start near your most important downtown stop." },
      { label: "Lunch", text: "Choose walkable food before moving the car." },
      { label: "Afternoon", text: "Add a park-access stop or indoor category depending on weather." },
      { label: "Evening", text: "Use the River Walk or an easy meal when the strip feels too packed." },
    ],
    freeAlternative: "River Walk, window-shopping and one park-side pause.",
    paidOption: "Downtown attraction category.",
    foodPairing: "Walkable Gatlinburg meal.",
    parkingWarning: "Park once if you can. Moving the car can waste the day.",
    crowdWarning: "Downtown gets tight during peak periods.",
    rainBackup: "Use indoor downtown categories and food nearby.",
    skip: "Skip driving between tiny downtown stops.",
    links: [
      { title: "Gatlinburg things to do", href: "/things-to-do/gatlinburg", description: "Walkable categories." },
      { title: "Restaurants Gatlinburg", href: "/restaurants/gatlinburg", description: "Food by situation." },
      { title: "Gatlinburg vs Pigeon Forge", href: "/gatlinburg-vs-pigeon-forge", description: "Compare the towns." },
    ],
  },
  {
    id: "budget-family",
    title: "Budget family day",
    match: ["Low budget", "Overspending", "Family with young kids", "Family with teens"],
    base: "Any base, but choose one corridor.",
    firstStop: "A free scenic or town-based anchor.",
    mainPlan: [
      { label: "Morning", text: "Start with a free scenic drive, visitor center-style stop or easy town walk." },
      { label: "Lunch", text: "Plan a simple meal before the group gets tired." },
      { label: "Afternoon", text: "Add one paid category only if it clearly fits the group." },
      { label: "Evening", text: "Use free lights, strolling or a low-pressure meal instead of another ticket." },
    ],
    freeAlternative: "Scenic drives, overlooks, visitor centers and walking areas.",
    paidOption: "One attraction category, not several.",
    foodPairing: "Budget-friendly meal near the route.",
    parkingWarning: "Parking costs and tags can still affect a low-budget day.",
    crowdWarning: "Cheap does not always mean low-crowd.",
    rainBackup: "Use a covered shopping or low-cost indoor category.",
    skip: "Skip coupon-chasing across town.",
    links: [
      { title: "Deals", href: "/deals", description: "Use savings without chasing them." },
      { title: "What to skip", href: "/what-to-skip", description: "Protect time and budget." },
      { title: "Things to do", href: "/things-to-do", description: "Match categories to the day." },
    ],
  },
  {
    id: "senior-low-walking",
    title: "Senior-friendly and low-walking starter plan",
    match: ["Grandparents / seniors", "Mobility-limited group", "Too much walking"],
    base: "Gatlinburg for walkable downtown or Townsend/Wears Valley for scenic pacing.",
    firstStop: "A scenic drive, overlook or visitor-center-style stop with cautious verification.",
    mainPlan: [
      { label: "Morning", text: "Choose one scenic road or easy stop and avoid rushing." },
      { label: "Lunch", text: "Eat somewhere with a simple parking plan if possible." },
      { label: "Afternoon", text: "Add a short overlook, town stop or rest period." },
      { label: "Evening", text: "Keep the evening near lodging or a walkable meal." },
    ],
    freeAlternative: "Overlooks, scenic roads and low-walking town stops.",
    paidOption: "Seated show, indoor attraction or guided category if verified later.",
    foodPairing: "Meal with the least parking and walking friction.",
    parkingWarning: "Accessibility details vary by exact stop. Verify before final plans.",
    crowdWarning: "Crowds make short walks and parking feel harder.",
    rainBackup: "Choose indoor seated categories and avoid long wet walks.",
    skip: "Skip pages or stops that promise easy access without clear details.",
    links: [
      { title: "Accessible Smokies", href: "/accessible-smokies", description: "Low-walking planning with caution." },
      { title: "Scenic drives", href: "/scenic-drives", description: "Nature with less walking." },
      { title: "Restaurants", href: "/restaurants", description: "Choose food by route." },
    ],
  },
  {
    id: "dollywood",
    title: "Dollywood-centered day",
    match: ["Dollywood day", "Pigeon Forge", "Long lines"],
    base: "Pigeon Forge or nearby lodging.",
    firstStop: "Dollywood as the main event.",
    mainPlan: [
      { label: "Morning", text: "Treat Dollywood as the core plan and keep the morning simple." },
      { label: "Lunch", text: "Eat in or near the same area instead of leaving for a complicated detour." },
      { label: "Afternoon", text: "Stay focused on the park or reset if the group is done." },
      { label: "Evening", text: "Choose a light meal or one easy nearby category." },
    ],
    freeAlternative: "A slower Pigeon Forge evening after the main paid day.",
    paidOption: "Theme park category.",
    foodPairing: "Pigeon Forge meal near your lodging or park route.",
    parkingWarning: "Verify current park details before you go.",
    crowdWarning: "Long lines can make add-ons unrealistic.",
    rainBackup: "Use a Pigeon Forge indoor category if the park day needs to shift.",
    skip: "Skip stacking multiple extra paid attractions around the park.",
    links: [
      { title: "Pigeon Forge things to do", href: "/things-to-do/pigeon-forge", description: "Parkway categories." },
      { title: "Pigeon Forge restaurants", href: "/restaurants/pigeon-forge", description: "Food after a park day." },
      { title: "Rainy day", href: "/rainy-day", description: "Backup plan." },
    ],
  },
  {
    id: "not-sure",
    title: "Not sure yet town chooser",
    match: ["Not sure yet", "Mixed group"],
    base: "Pick the base town first.",
    firstStop: "Choose between walkability, attractions, value, quiet or NC-side access.",
    mainPlan: [
      { label: "Morning", text: "List what your group actually wants: park, attractions, food, quiet or low walking." },
      { label: "Lunch", text: "Use food as a route anchor, not a separate chase." },
      { label: "Afternoon", text: "Choose the town that reduces driving for the main thing." },
      { label: "Evening", text: "Keep the first evening easy until you know the area." },
    ],
    freeAlternative: "Start with town comparison and scenic options before buying tickets.",
    paidOption: "Only choose paid categories after the town decision.",
    foodPairing: "Food near your base town.",
    parkingWarning: "The wrong base can turn every day into a drive.",
    crowdWarning: "A crowded town can still be the right fit if walking matters.",
    rainBackup: "Choose a base with indoor categories nearby.",
    skip: "Skip booking for a view alone.",
    links: [
      { title: "Where to stay", href: "/where-to-stay", description: "Town comparison." },
      { title: "Gatlinburg vs Pigeon Forge", href: "/gatlinburg-vs-pigeon-forge", description: "The main decision." },
      { title: "How many days", href: "/how-many-days", description: "Set the trip shape." },
    ],
  },
  {
    id: "nc-side",
    title: "NC-side / Cherokee / Bryson City starter result",
    match: ["NC side / Cherokee / Bryson City"],
    base: "Cherokee, Bryson City or another NC-side base.",
    firstStop: "NC-side park access or Deep Creek-style outing after verifying current conditions.",
    mainPlan: [
      { label: "Morning", text: "Start with the NC-side park or town route rather than forcing a TN attraction day." },
      { label: "Lunch", text: "Eat near the same side of the mountains." },
      { label: "Afternoon", text: "Add elk, Deep Creek, scenic roads or a railroad-style category if it fits." },
      { label: "Evening", text: "Keep the evening on the NC side unless conditions and time make a crossing sensible." },
    ],
    freeAlternative: "NC-side scenic stops, visitor centers and river areas.",
    paidOption: "Railroad-style, museum or guided category if verified later.",
    foodPairing: "Cherokee or Bryson City area meal.",
    parkingWarning: "Verify current road status before routing across the mountains.",
    crowdWarning: "Do not assume the NC side is empty in peak seasons.",
    rainBackup: "Use town-based indoor categories or a food-first day.",
    skip: "Skip treating Cherokee or Bryson City as a quick side trip from a Dollywood-heavy plan.",
    links: [
      { title: "Where to stay", href: "/where-to-stay", description: "Both-state base logic." },
      { title: "Scenic drives", href: "/scenic-drives", description: "NC-side route cautions." },
      { title: "First time Smokies", href: "/first-time-smokies", description: "Build a calmer first trip." },
    ],
  },
];

export type ResearchPlannerAnswerKey =
  | "group"
  | "base"
  | "day"
  | "risk"
  | "paceBudget"
  | "tripLength"
  | "season"
  | "mobility"
  | "crowd"
  | "rainNeed";

export type ResearchPlannerOption = {
  label: string;
  detail: string;
};

export type ResearchPlannerQuestion = {
  key: ResearchPlannerAnswerKey;
  label: string;
  helper: string;
  options: ResearchPlannerOption[];
};

export type ResearchPlannerAnswers = Partial<Record<ResearchPlannerAnswerKey, string>>;

export type ResearchPlannerPlan = {
  id: string;
  title: string;
  match: Partial<Record<ResearchPlannerAnswerKey, string[]>>;
  bestStartingBase: string;
  bestFor: string;
  weakFit: string;
  mainAnchor: string;
  secondaryStop: string;
  optionalAddOn: string;
  foodRestStrategy: string;
  parkingMovementWarning: string;
  crowdStrategy: string;
  rainBackup: string;
  mobilityNote: string;
  budgetNote: string;
  whatToSkip: string;
  officialSourceCaution: string;
  whyItFits: string;
  bestNextLink: LinkItem;
  relatedGuideLinks: LinkItem[];
};

export const officialSourceCaution =
  "Check official status before you go. Do not rely on this for current hours, prices or closures. Road, weather and park conditions can change.";

const plannerRelated = (...hrefs: string[]) => guideLinks.filter((link) => hrefs.includes(link.href));

export const researchPlannerQuestions: ResearchPlannerQuestion[] = [
  {
    key: "group",
    label: "Who is going?",
    helper: "Pick the group that changes the plan the most.",
    options: [
      { label: "Family with kids", detail: "Kid patience, bathrooms, food timing and one strong anchor." },
      { label: "Toddlers / stroller", detail: "Short blocks, stroller reality, easy exits and indoor backup." },
      { label: "Grandparents / limited mobility", detail: "Parking, bathrooms, benches, short walks and seated resets." },
      { label: "Adults / couples", detail: "Scenery, food, calmer pacing and fewer kid-driven stops." },
      { label: "First-time mixed group", detail: "A simple plan that avoids common first-trip mistakes." },
    ],
  },
  {
    key: "base",
    label: "Where are you starting?",
    helper: "The same activity can be smart or messy depending on the base.",
    options: [
      { label: "Not sure yet", detail: "Let the planner choose the least-friction base." },
      { label: "Gatlinburg", detail: "Walkable strip, park access, tighter parking." },
      { label: "Pigeon Forge", detail: "Family attractions, Dollywood, Parkway corridor." },
      { label: "Sevierville", detail: "Value base, outlets, local-business pacing." },
      { label: "Townsend", detail: "Quiet side, Cades Cove, scenic drives." },
      { label: "Wears Valley", detail: "Cabins, views, Foothills Parkway, slower route logic." },
      { label: "Cherokee / Bryson City", detail: "NC-side access, Deep Creek, elk, Cataloochee-style planning." },
    ],
  },
  {
    key: "day",
    label: "What kind of day do you want?",
    helper: "This chooses the anchor. Everything else has to fit around it.",
    options: [
      { label: "First-time overview", detail: "One town anchor, one scenic piece, one backup." },
      { label: "Kid attraction day", detail: "WonderWorks, Parrot Mountain, The Island or a Parkway anchor." },
      { label: "Dollywood / attraction day", detail: "Treat Dollywood or another paid anchor as the main event." },
      { label: "Cades Cove / park day", detail: "Slow scenic loop, Townsend/Wears Valley, early timing." },
      { label: "Scenic drive / park roads", detail: "Roaring Fork, Foothills Parkway, Kuwohi, Newfound Gap or NC-side routes." },
      { label: "Food and shopping", detail: "Pick a meal or town corridor first, then add one nearby stop." },
      { label: "NC-side park day", detail: "Cherokee, Bryson City, Deep Creek, Cataloochee or elk-style planning." },
    ],
  },
  {
    key: "risk",
    label: "What could ruin the day?",
    helper: "The plan should protect against the pain point, not ignore it.",
    options: [
      { label: "Traffic / parking", detail: "Avoid town-hopping and repeated parking changes." },
      { label: "Rain", detail: "Use indoor anchors and keep outdoor swaps realistic." },
      { label: "Overspending", detail: "Lead with free scenery, visitor centers and one paid stop only if it earns the day." },
      { label: "Too much walking", detail: "Plan parking, bathrooms and short stops first." },
      { label: "Crowds / long lines", detail: "Use early timing, quieter bases and fewer anchors." },
      { label: "Mountain roads / bad GPS", detail: "Download maps and avoid casual cross-mountain routing." },
    ],
  },
  {
    key: "paceBudget",
    label: "What is your budget and pace?",
    helper: "This decides whether paid attractions lead or support the day.",
    options: [
      { label: "Low cost / easy pace", detail: "Free or cheap first, fewer stops, simple food." },
      { label: "Mixed budget / medium pace", detail: "One paid anchor plus nearby support." },
      { label: "Paid attractions OK / full day", detail: "Tickets are fine, but do not stack blindly." },
      { label: "Comfort over quantity", detail: "Shorter moves, seats, resets and less backtracking." },
    ],
  },
  {
    key: "tripLength",
    label: "How much time do you have?",
    helper: "Half-day and three-day plans should not get the same recommendation.",
    options: [
      { label: "Half day", detail: "One anchor, one meal or reset, one backup." },
      { label: "One day", detail: "One main route with a realistic secondary stop." },
      { label: "Two days", detail: "Split park/scenery and attraction/town time." },
      { label: "Three-plus days", detail: "Room for park, attractions and a flexible weather day." },
    ],
  },
  {
    key: "season",
    label: "When are you visiting?",
    helper: "Season changes crowds, road/weather risk and what to verify.",
    options: [
      { label: "Spring", detail: "Blooms, changing weather, closures and road checks." },
      { label: "Summer", detail: "Heat, storms, crowds and midday indoor resets." },
      { label: "Fall", detail: "Crowds, color-chasing, scenic-drive pressure." },
      { label: "Winter", detail: "Road/weather checks, Winterfest, fewer daylight hours." },
      { label: "Not sure", detail: "Keep the plan season-flexible." },
    ],
  },
  {
    key: "mobility",
    label: "Any walking limits?",
    helper: "Low-walking days need parking and access logic, not vague easy labels.",
    options: [
      { label: "No issue", detail: "Normal walking is fine." },
      { label: "Light walking only", detail: "Short walks, overlooks and fewer parking changes." },
      { label: "Stroller", detail: "Stroller truth matters; paved does not always mean stroller-simple." },
      { label: "Grandparents / limited mobility", detail: "Bathrooms, benches, short stops and verified access matter." },
    ],
  },
  {
    key: "crowd",
    label: "How do you feel about crowds?",
    helper: "Crowd tolerance changes the town, timing and route.",
    options: [
      { label: "Avoid crowds", detail: "Early starts, quieter bases, fewer popular add-ons." },
      { label: "Balanced", detail: "Use popular places, but keep the route disciplined." },
      { label: "Do not care", detail: "Bigger attractions and busy towns are fine." },
    ],
  },
  {
    key: "rainNeed",
    label: "How rain-safe does the day need to be?",
    helper: "Rain can change the day without killing it if the backup is close.",
    options: [
      { label: "Must stay indoors", detail: "Indoor anchor first, nearby food, no wishful outdoor plan." },
      { label: "Flexible backup", detail: "Keep an indoor swap and one short outdoor window." },
      { label: "Outdoor if weather allows", detail: "Start outdoors if conditions cooperate, but keep a route-safe fallback." },
    ],
  },
];

export const researchPlannerPlans: ResearchPlannerPlan[] = [
  {
    id: "family-rain-pigeon-forge",
    title: "Pigeon Forge rainy-day family decision plan",
    match: {
      group: ["Family with kids", "Toddlers / stroller"],
      base: ["Pigeon Forge", "Sevierville", "Not sure yet"],
      day: ["Kid attraction day", "First-time overview"],
      risk: ["Rain", "Traffic / parking"],
      rainNeed: ["Must stay indoors", "Flexible backup"],
      paceBudget: ["Mixed budget / medium pace", "Paid attractions OK / full day"],
    },
    bestStartingBase: "Pigeon Forge or Sevierville, depending on lodging and food plans.",
    bestFor: "Families that need one indoor-friendly anchor, nearby food and a clear exit if kids fade.",
    weakFit: "Weak fit if the group wants quiet park scenery as the whole point of the day.",
    mainAnchor: "WonderWorks, The Island area, indoor mini golf/arcades or a Ripley's-style indoor category after checking current details.",
    secondaryStop: "Parrot Mountain or a simple Parkway stop only if weather and kid energy still cooperate.",
    optionalAddOn: "Use Dollywood only as a full-day anchor, not as a rainy-day add-on after multiple smaller tickets.",
    foodRestStrategy: "Eat near the indoor anchor or lodging. A hungry family should not cross the county for one more stop.",
    parkingMovementWarning: "Pigeon Forge works for attraction days, but the Parkway punishes backtracking and repeated parking changes.",
    crowdStrategy: "When rain hits, everyone looks indoors. Pick one anchor early and keep the rest flexible.",
    rainBackup: "This is the rain-safe plan. If showers break, use a short outdoor window instead of rebuilding the whole day.",
    mobilityNote: "For toddlers or strollers, verify surfaces and keep bathroom breaks close. Paved does not automatically mean stroller-simple.",
    budgetNote: "One paid anchor plus food is usually better than three smaller impulse tickets.",
    whatToSkip: "Skip trying to rescue every outdoor plan in the same wet day.",
    officialSourceCaution,
    whyItFits: "It matches the research path for family + rain + Pigeon Forge: indoor anchor, nearby food, no county-wide list, and one flexible outdoor swap.",
    bestNextLink: { title: "Rainy day guide", href: "/rainy-day", description: "Build the wet-weather day by town." },
    relatedGuideLinks: plannerRelated("/things-to-do", "/things-to-do/pigeon-forge", "/smokies-parking-trolley-guide", "/deals"),
  },
  {
    id: "low-walking-townsend",
    title: "Townsend low-walking quiet-side plan",
    match: {
      group: ["Grandparents / limited mobility", "Adults / couples"],
      base: ["Townsend", "Wears Valley", "Not sure yet"],
      day: ["Cades Cove / park day", "Scenic drive / park roads"],
      risk: ["Too much walking", "Crowds / long lines"],
      mobility: ["Light walking only", "Grandparents / limited mobility"],
      crowd: ["Avoid crowds"],
      paceBudget: ["Comfort over quantity", "Low cost / easy pace"],
    },
    bestStartingBase: "Townsend or Wears Valley.",
    bestFor: "Visitors who want scenery, calmer pacing and less walking before anything else.",
    weakFit: "Weak fit for visitors who want constant entertainment, nightlife or a packed paid-attraction day.",
    mainAnchor: "Foothills Parkway, a Townsend-side scenic stop or Cades Cove only if the group can give the loop real time.",
    secondaryStop: "Sugarlands Visitor Center, a quiet meal, a short overlook or Wears Valley reset depending on the route.",
    optionalAddOn: "Sugarlands Valley Nature Trail can be a better low-walking nature option than vague easy-hike promises, but verify current access.",
    foodRestStrategy: "Plan the meal before or after the scenic route, not as a late cross-county detour.",
    parkingMovementWarning: "Low-walking days need parking, bathrooms and short stops planned first. Scenic does not mean parking-free.",
    crowdStrategy: "Start early for Cades Cove or popular overlooks; avoid forcing peak-window scenic routes.",
    rainBackup: "Use Townsend, visitor-center-style stops or a slow food route if rain makes the loop unpleasant.",
    mobilityNote: "Accessibility varies by exact stop. Verify surfaces, bathrooms, benches and parking before relying on the plan.",
    budgetNote: "This plan can stay low-cost because scenery, overlooks and visitor centers can carry the day.",
    whatToSkip: "Skip any plan that promises easy access without naming the parking and walking reality.",
    officialSourceCaution,
    whyItFits: "It follows the research recommendation for seniors/mobility-limited visitors: scenic drives, short stops, bathrooms, benches and quiet-side pacing.",
    bestNextLink: { title: "Accessible Smokies", href: "/accessible-smokies", description: "Low-walking ideas with cautions." },
    relatedGuideLinks: plannerRelated("/cades-cove", "/scenic-drives", "/where-to-stay", "/restaurants"),
  },
  {
    id: "gatlinburg-first-time-scenic",
    title: "Gatlinburg first-time scenery-and-walkability plan",
    match: {
      group: ["First-time mixed group", "Adults / couples"],
      base: ["Gatlinburg"],
      day: ["First-time overview", "Scenic drive / park roads", "Food and shopping"],
      risk: ["Traffic / parking", "Crowds / long lines"],
      tripLength: ["One day", "Two days"],
      crowd: ["Balanced", "Do not care"],
    },
    bestStartingBase: "Gatlinburg.",
    bestFor: "First-time visitors who want a town-and-park sampler without moving the car all day.",
    weakFit: "Weak fit if the group hates crowds, tight streets or downtown walking.",
    mainAnchor: "Park once for the Gatlinburg strip, then pair it with Sugarlands Visitor Center or Roaring Fork Motor Nature Trail if conditions fit.",
    secondaryStop: "Use Anakeesta, Ripley's or Ober as a single paid category only if it matches the group's energy and budget.",
    optionalAddOn: "Kuwohi or Newfound Gap can be a bigger scenic move on a longer day, but current road/weather status matters.",
    foodRestStrategy: "Choose food near the walking route. Lunch should not become a new parking mission.",
    parkingMovementWarning: "Gatlinburg works best when visitors park once and walk. Moving the car between tiny downtown stops can waste the day.",
    crowdStrategy: "Use an earlier start or a calmer park-side reset when the strip gets tight.",
    rainBackup: "If rain tightens the day, use Ripley's-style indoor categories, food and shopping near the same parking plan.",
    mobilityNote: "Downtown walkability is useful, but limited-mobility groups still need verified parking, surfaces and rest points.",
    budgetNote: "A walkable town plan can stay moderate if you pick one paid category and skip the add-on pile.",
    whatToSkip: "Skip a four-town sampler. Gatlinburg, Pigeon Forge, Cades Cove and Dollywood do not belong in one first-time day.",
    officialSourceCaution,
    whyItFits: "It uses the research distinction that Gatlinburg is strongest as a park-once, walkable gateway with park access nearby.",
    bestNextLink: { title: "Gatlinburg vs Pigeon Forge", href: "/gatlinburg-vs-pigeon-forge", description: "Choose the better town for the trip." },
    relatedGuideLinks: plannerRelated("/things-to-do/gatlinburg", "/restaurants/gatlinburg", "/scenic-drives", "/smokies-parking-trolley-guide"),
  },
  {
    id: "budget-sevierville-not-sure",
    title: "Budget-conscious Sevierville corridor plan",
    match: {
      group: ["Family with kids", "First-time mixed group", "Toddlers / stroller"],
      base: ["Sevierville", "Not sure yet"],
      day: ["Kid attraction day", "Food and shopping", "First-time overview"],
      risk: ["Overspending", "Traffic / parking"],
      paceBudget: ["Low cost / easy pace", "Mixed budget / medium pace"],
      tripLength: ["Half day", "One day"],
    },
    bestStartingBase: "Sevierville or the least-congested side of your lodging route.",
    bestFor: "Families trying to avoid overspending while still giving the day a real anchor.",
    weakFit: "Weak fit if the group wants the full Gatlinburg strip or a Dollywood-centered day.",
    mainAnchor: "Start with a free or lower-cost scenic/town stop, outlet/local-business pacing or one paid family category that truly fits.",
    secondaryStop: "Use Pigeon Forge Parkway only for one chosen anchor, not a string of impulse stops.",
    optionalAddOn: "The Island, WonderWorks or Parrot Mountain can work if it replaces other paid stops instead of adding to them.",
    foodRestStrategy: "Pick a simple meal near the route. Savings vanish fast when a deal sends the group across town.",
    parkingMovementWarning: "Parking costs, park tags and repeated moves can still affect a low-budget day.",
    crowdStrategy: "Cheap does not always mean low-crowd. Keep the route short and avoid chasing every coupon.",
    rainBackup: "Use covered shopping, indoor family categories or a food-first reset if weather turns.",
    mobilityNote: "For stroller or grandparent needs, choose fewer stops with simpler parking and bathrooms.",
    budgetNote: "Lead with free scenery, visitor centers, town walks and one paid stop only if it earns the time.",
    whatToSkip: "Skip coupon-chasing across town and stacking small paid stops because each one looks affordable.",
    officialSourceCaution,
    whyItFits: "It matches the research budget path: free/cheap first, route discipline, one paid anchor at most, and no deal-led itinerary.",
    bestNextLink: { title: "Deals", href: "/deals", description: "Use savings only when they fit the trip." },
    relatedGuideLinks: plannerRelated("/things-to-do", "/what-to-skip", "/where-to-stay", "/rainy-day"),
  },
  {
    id: "fall-cades-cove-crowd-sensitive",
    title: "Crowd-sensitive Cades Cove and scenic-drive plan",
    match: {
      group: ["Adults / couples", "First-time mixed group"],
      base: ["Townsend", "Wears Valley", "Not sure yet"],
      day: ["Cades Cove / park day", "Scenic drive / park roads"],
      risk: ["Crowds / long lines", "Traffic / parking", "Mountain roads / bad GPS"],
      paceBudget: ["Low cost / easy pace", "Comfort over quantity"],
      season: ["Fall", "Summer", "Spring"],
      mobility: ["No issue", "Light walking only"],
      crowd: ["Avoid crowds"],
      tripLength: ["One day", "Two days", "Three-plus days"],
    },
    bestStartingBase: "Townsend or Wears Valley.",
    bestFor: "Park-heavy visitors who care more about scenery, timing and crowd avoidance than attractions.",
    weakFit: "Weak fit if the group wants a quick scenic stop between Pigeon Forge tickets.",
    mainAnchor: "Cades Cove with an early start, or Foothills Parkway/Roaring Fork if the loop timing does not fit.",
    secondaryStop: "Use a Townsend meal, Wears Valley reset, Sugarlands Visitor Center or a shorter scenic stop.",
    optionalAddOn: "Kuwohi/Newfound Gap can be powerful on the right day, but verify road and weather conditions before routing there.",
    foodRestStrategy: "Eat before or after the scenic route. Do not put lunch in the middle of a rushed loop.",
    parkingMovementWarning: "Cades Cove can take longer than visitors expect. Cell service and GPS reliability can be issues around park/scenic routes, so download maps.",
    crowdStrategy: "Early timing matters. Fall color and peak weekends can turn scenic drives into slow traffic.",
    rainBackup: "Rain may reduce visibility, but it does not always kill the day. Shift to visitor centers, a shorter route or a food-first town reset.",
    mobilityNote: "Use overlooks and visitor-center-style stops for lower walking; verify exact access and bathrooms.",
    budgetNote: "This plan can stay mostly free, but parking tags and route logistics still matter.",
    whatToSkip: "Skip treating Cades Cove as a quick add-on or mixing it casually with a packed TN-side attraction day.",
    officialSourceCaution,
    whyItFits: "It follows the research warning that Cades Cove and scenic-drive days are timing-sensitive, slow by design and best from the quiet side.",
    bestNextLink: { title: "Cades Cove", href: "/cades-cove", description: "Plan the loop with time." },
    relatedGuideLinks: plannerRelated("/scenic-drives", "/smokies-parking-trolley-guide", "/accessible-smokies", "/what-to-skip"),
  },
  {
    id: "nc-side-deep-creek-cataloochee",
    title: "NC-side Cherokee and Bryson City plan",
    match: {
      base: ["Cherokee / Bryson City"],
      day: ["NC-side park day", "Scenic drive / park roads"],
      risk: ["Mountain roads / bad GPS", "Crowds / long lines"],
      crowd: ["Avoid crowds", "Balanced"],
    },
    bestStartingBase: "Cherokee, Bryson City or another NC-side base.",
    bestFor: "Visitors focused on Deep Creek, Cataloochee elk, NC-side scenery or a trip that should not be forced through Pigeon Forge.",
    weakFit: "Weak fit for a Dollywood-heavy or Pigeon Forge-heavy day.",
    mainAnchor: "Deep Creek, Cherokee-area park access or Cataloochee-style elk/scenic planning after checking current status.",
    secondaryStop: "Use a same-side meal, visitor center, river area or scenic road instead of crossing the mountains late.",
    optionalAddOn: "Kuwohi/Newfound Gap can connect sides only when time, roads and weather make sense.",
    foodRestStrategy: "Keep food on the NC side. A cross-mountain meal detour can wreck the route.",
    parkingMovementWarning: "NC-side trips need their own logic. Do not casually mix them into a packed TN-side day.",
    crowdStrategy: "The NC side can still crowd in peak windows. Start with the route that matters most.",
    rainBackup: "Use town-based indoor categories, visitor centers or food-first pacing if weather weakens scenery.",
    mobilityNote: "River, trail and elk-viewing areas vary by surface and access. Verify exact conditions.",
    budgetNote: "Scenery and visitor-center-style stops can keep the day moderate if paid add-ons stay optional.",
    whatToSkip: "Skip treating Cherokee, Bryson City, Deep Creek or Cataloochee as quick side trips from a full TN attraction plan.",
    officialSourceCaution,
    whyItFits: "It protects the both-states strategy from the research: NC-side trips are valid, but they need separate routing and current road/status checks.",
    bestNextLink: { title: "Scenic drives", href: "/scenic-drives", description: "Choose the right road and verify conditions." },
    relatedGuideLinks: plannerRelated("/where-to-stay", "/accessible-smokies", "/first-time-smokies", "/smokies-parking-trolley-guide"),
  },
  {
    id: "dollywood-full-day",
    title: "Dollywood-centered Pigeon Forge day",
    match: {
      base: ["Pigeon Forge"],
      day: ["Dollywood / attraction day"],
      paceBudget: ["Paid attractions OK / full day", "Mixed budget / medium pace"],
      risk: ["Crowds / long lines", "Traffic / parking"],
      tripLength: ["One day", "Two days", "Three-plus days"],
    },
    bestStartingBase: "Pigeon Forge or nearby lodging.",
    bestFor: "Visitors who want Dollywood or a major paid attraction to be the main event.",
    weakFit: "Weak fit for low-cost, low-walking or quiet scenic days.",
    mainAnchor: "Dollywood as the core plan, with current park details checked before final plans.",
    secondaryStop: "A simple Pigeon Forge meal or lodging reset. Add The Island or another Parkway stop only if the group has real energy.",
    optionalAddOn: "WonderWorks, dinner-show categories or indoor mini golf can become the backup, not an extra pile-on.",
    foodRestStrategy: "Keep food close to the park or lodging. Leaving for a complicated detour usually costs more than it helps.",
    parkingMovementWarning: "Do not add Gatlinburg, Cades Cove or a long scenic drive around a Dollywood day.",
    crowdStrategy: "Long lines can make add-ons unrealistic. Protect the anchor first.",
    rainBackup: "Use a Pigeon Forge indoor category if the park day needs to shift after checking current details.",
    mobilityNote: "A full attraction day can be physically long. Plan rests and verify access needs.",
    budgetNote: "Paid attractions are fine here, but the budget should center on one main ticketed anchor.",
    whatToSkip: "Skip stacking multiple extra paid attractions around the park.",
    officialSourceCaution,
    whyItFits: "It follows the research rule that paid attraction days need one anchor, nearby food and no overstacked Parkway plan.",
    bestNextLink: { title: "Dollywood day plan", href: "/dollywood-day-plan", description: "Treat the park as the main event." },
    relatedGuideLinks: plannerRelated("/things-to-do/pigeon-forge", "/restaurants/pigeon-forge", "/rainy-day", "/what-to-skip"),
  },
  {
    id: "laurel-kuwohi-current-status",
    title: "Scenic-drive plan with current-status cautions",
    match: {
      day: ["Scenic drive / park roads", "First-time overview"],
      risk: ["Mountain roads / bad GPS", "Traffic / parking"],
      season: ["Spring", "Summer", "Fall", "Winter"],
      rainNeed: ["Outdoor if weather allows", "Flexible backup"],
    },
    bestStartingBase: "Gatlinburg for Sugarlands/Roaring Fork, Townsend/Wears Valley for Foothills Parkway, or NC side for Cherokee/Bryson City routes.",
    bestFor: "Visitors who want scenery but need the plan to respect road, weather and closure uncertainty.",
    weakFit: "Weak fit for groups that need guaranteed indoor entertainment or fixed schedules.",
    mainAnchor: "Roaring Fork Motor Nature Trail, Foothills Parkway, Newfound Gap/Kuwohi or another scenic route chosen by base and current conditions.",
    secondaryStop: "Sugarlands Visitor Center, an overlook, a same-side meal or a short town reset.",
    optionalAddOn: "Laurel Falls should be treated with closure caution; verify official status before building a waterfall plan around it.",
    foodRestStrategy: "Pair scenery with food on the return route, not a far detour.",
    parkingMovementWarning: "Road, weather and park conditions can change. Cell service and GPS can be unreliable, so download maps before park routes.",
    crowdStrategy: "Start earlier for popular scenic roads and fall-color windows; do not try to sample every drive.",
    rainBackup: "If visibility drops, switch to visitor centers, food/shopping or a shorter same-side route.",
    mobilityNote: "Scenic drives can reduce walking, but overlooks and visitor centers still need access checks.",
    budgetNote: "Scenic routes are often budget-friendly, but parking tags and route logistics still matter.",
    whatToSkip: "Skip old advice that ignores Kuwohi naming, Laurel Falls closure cautions or current road impacts.",
    officialSourceCaution,
    whyItFits: "It brings the research accuracy traps into the planner: Kuwohi, Laurel Falls, road/weather checks and map-download logic.",
    bestNextLink: { title: "Scenic drives", href: "/scenic-drives", description: "Choose drives by base and conditions." },
    relatedGuideLinks: plannerRelated("/parking-tag", "/accessible-smokies", "/first-time-smokies", "/smokies-parking-trolley-guide"),
  },
];

export const dealPlaceholders = [
  {
    offer: "No verified public deals listed yet.",
    expiration: "Verify before using any future offer.",
    terms: "Future offers must include clear terms and expiration before publishing.",
    status: "Needs verification",
    bestFor: "Visitors who already know the deal fits their route.",
  },
];

export const restaurantCategoryPlaceholders = [
  "Breakfast and pancakes",
  "BBQ",
  "Family-friendly meals",
  "Date night",
  "Budget eats",
  "Near Dollywood",
  "After Cades Cove",
  "Rainy-day meals",
];

const sourceLine = "Details can change. Verify time-sensitive rules, closures, schedules, accessibility details, prices and hours with the official source before final plans.";

const related = (...hrefs: string[]) => guideLinks.filter((link) => hrefs.includes(link.href));

export const guidePages: Record<string, GuidePageData> = {
  "/where-to-stay": {
    title: "Where to Stay in the Smokies",
    description: "Choose the right Smoky Mountains base town by trip type, budget, walkability, crowds, park access and family needs.",
    directAnswer: "Most visitors should choose their base town before choosing attractions. Gatlinburg is best for walkability and park access. Pigeon Forge is best for families, Dollywood and attractions. Sevierville often works for value and gateway convenience. Townsend works best for quiet trips, Cades Cove and scenic drives.",
    sections: [
      { title: "Quick answer", body: "Start with the day you want most, then choose the town that makes that day easier. A cabin view is not helpful if every plan becomes a long drive." },
      { title: "Town comparison table", body: "Gatlinburg favors walking and park access. Pigeon Forge favors family attractions and easier parking. Sevierville favors value and gateway convenience. Townsend favors the quiet side and Cades Cove. Wears Valley favors cabins and slower scenic access. Cherokee and Bryson City favor the NC side." },
      ...towns.map((town) => ({ title: town.name, body: `Best for: ${town.bestFor} Skip if: ${town.skipIf} Common mistake: ${town.mistake}` })),
      { title: "Best town by trip type", body: "First-timers often compare Gatlinburg and Pigeon Forge first. Crowd-avoiders should look hard at Townsend or Wears Valley. NC-side travelers should not force a TN-heavy route." },
      { title: "Common mistakes", body: "The big mistakes are booking before choosing the trip shape, treating every town as close together and ignoring parking, traffic and walking load." },
    ],
    links: related("/plan-your-trip", "/gatlinburg-vs-pigeon-forge", "/first-time-smokies", "/how-many-days"),
    bestFor: ["Visitors choosing lodging", "Families comparing Gatlinburg and Pigeon Forge", "First-timers who need a base town before booking"],
    skipIf: ["You already booked and only need a single restaurant", "You need current hotel rates, which should be verified elsewhere"],
  },
  "/gatlinburg-vs-pigeon-forge": {
    title: "Gatlinburg vs Pigeon Forge",
    description: "Choose between Gatlinburg and Pigeon Forge by walkability, family needs, parking, park access, food, attractions and crowd tolerance.",
    directAnswer: "Choose Gatlinburg if walkability, downtown access and proximity to the national park matter most. Choose Pigeon Forge if your group wants family attractions, Dollywood, dinner shows and easier stop-by-stop parking. Choose Sevierville for value or Townsend for quiet-side park days.",
    sections: [
      { title: "Choose Gatlinburg if", body: "You want to park once, walk downtown, reach the park quickly and keep food and attractions close together." },
      { title: "Choose Pigeon Forge if", body: "You want a family attraction corridor, Dollywood categories, dinner shows, mini golf, arcades and more room around many stops." },
      { title: "Choose Sevierville if", body: "You want value lodging, outlets, gateway convenience or a calmer base outside the busiest middle of the strip." },
      { title: "Choose Townsend if", body: "You want Cades Cove, scenic drives, quieter evenings and less attraction density." },
      { title: "Walkability", body: "Gatlinburg is the stronger walkable town. Pigeon Forge is more corridor-based, so plan around driving and parking from stop to stop." },
      { title: "Family trip", body: "Pigeon Forge usually gives families more attraction categories in one corridor. Gatlinburg can work well when the family wants a downtown day and shorter park access." },
      { title: "Parking", body: "Gatlinburg rewards a park-once plan. Pigeon Forge can be easier per stop, but the Parkway still needs restraint." },
      { title: "Park access", body: "Gatlinburg is the stronger TN-side park gateway. Townsend is stronger for quiet-side park plans and Cades Cove." },
      { title: "Food and attractions", body: "Choose food by the route you are already using. Driving across town for one meal can wreck a good plan." },
      { title: "Best choice by visitor type", body: "First-timers with mixed goals should compare both. Families often lean Pigeon Forge. Walkers lean Gatlinburg. Quiet-side travelers lean Townsend." },
    ],
    links: related("/where-to-stay", "/plan-your-trip", "/restaurants", "/things-to-do"),
    bestFor: ["Visitors deciding between the two main TN gateway towns", "Families choosing a base", "First-timers who need a clear tradeoff"],
    skipIf: ["You want a live hotel price comparison", "Your whole trip is already locked to the NC side"],
  },
  "/how-many-days": {
    title: "How Many Days Do You Need in the Smokies?",
    description: "Pick a realistic Smokies trip length for first-timers, families, seniors, rainy weather and Cades Cove without cramming the map.",
    directAnswer: "Most first-time visitors do best with three days: one park or scenic day, one attraction or town day and one flexible day for weather, crowds or a slower morning. One day can work if you choose a tight plan. Four or more days lets you add Cades Cove, Dollywood, a scenic drive and a lower-pressure food or shopping day.",
    sections: [
      { title: "One day", body: "Choose one area and one anchor. Do not try to see Gatlinburg, Pigeon Forge, Cades Cove and the NC side in the same day." },
      { title: "Two days", body: "Use one park or scenic day and one town or attraction day. Keep the second evening flexible." },
      { title: "Three days", body: "This is the easiest first-timer shape: scenic or park day, attractions or town day, flexible recovery day." },
      { title: "Four or more days", body: "Add slower routes, a Cades Cove day, Dollywood, food, shopping and rainy backups without turning each day into a race." },
      { title: "With kids", body: "Kids usually do better with one main thing per day plus food and rest. Paid add-ons stack up fast." },
      { title: "With seniors", body: "Build in parking, seating, bathrooms and shorter walking sections. Verify accessibility details before final plans." },
      { title: "If it rains", body: "A flexible day saves the trip. Move indoor categories into that slot instead of forcing wet outdoor plans." },
      { title: "What not to cram", body: "Do not cram Cades Cove, Dollywood, downtown Gatlinburg and a long scenic drive into one day." },
    ],
    links: related("/plan-your-trip", "/where-to-stay", "/rainy-day", "/cades-cove"),
  },
  "/best-time-to-visit": {
    title: "Best Time to Visit the Smokies",
    description: "Choose the best Smokies season for lower crowds, families, fall color, Christmas lights and weather risk with source-check reminders.",
    directAnswer: "The best time depends on what would ruin the trip. Spring and fall can be strong overall, summer works for families with school schedules and winter can be good for lights and quieter pacing. Fall color, holiday events, road access and weather vary, so verify current conditions before final plans.",
    sections: [
      { title: "Best overall", body: "Shoulder seasons often balance weather, scenery and crowds better than peak holiday periods." },
      { title: "Best for lower crowds", body: "Non-holiday weekdays and slower seasons are usually easier than peak summer, fall weekends and big event windows." },
      { title: "Best for families", body: "Families often choose summer or school breaks. Keep the plan simpler because crowds and heat can wear people out." },
      { title: "Best for fall color", body: "Fall color changes by elevation and weather. Use official and local current-condition sources before timing a color-focused trip." },
      { title: "Best for Christmas and Winterfest", body: "Winter light seasons can be good for town-based trips. Verify event dates before you go." },
      { title: "Worst times for crowds", body: "Major holiday periods, peak fall weekends and big local event windows can make short drives feel long." },
      { title: "Weather and road caution", body: sourceLine },
      { title: "Verify current conditions", body: "Before final plans, check official park alerts and road status, especially for cross-mountain routes." },
    ],
    links: related("/plan-your-trip", "/rainy-day", "/scenic-drives", "/first-time-smokies"),
  },
  "/parking-tag": {
    title: "Smoky Mountains Parking Tag Guide",
    description: "Understand Smoky Mountains parking tag basics, what a tag does not guarantee and where to verify current rules before parking.",
    directAnswer: "Many visitors parking inside Great Smoky Mountains National Park may need a parking tag, but rules, purchase options and enforcement details can change. A parking tag does not reserve a space, does not remove traffic and does not replace checking official park guidance before you go.",
    sections: [
      { title: "Who may need it", body: "If you plan to park inside the national park, verify current parking tag rules with the official park source before final plans." },
      { title: "What it does not do", body: "A parking tag does not guarantee a parking space, reduce traffic or make a full lot usable." },
      { title: "Where to verify", body: "Use the official Great Smoky Mountains National Park parking tag and fees pages before you go." },
      { title: "Common mistake", body: "The common mistake is buying or skipping a tag based on old blog information." },
      { title: "Rental car caution", body: "If you use a rental vehicle, verify how the tag should be displayed or handled before leaving town." },
      { title: "Parking does not guarantee a space", body: "Popular trailheads, overlooks and scenic areas can fill even when you have the required tag." },
    ],
    links: related("/first-time-smokies", "/cades-cove", "/scenic-drives", "/smokies-parking-trolley-guide"),
  },
  "/first-time-smokies": {
    title: "First Time in the Smokies",
    description: "A simple first-time Smokies planning guide for choosing a base town, setting a three-day shape and avoiding common mistakes.",
    directAnswer: "First-time visitors should pick a base town first, then build a simple trip shape: one park or scenic day, one town or attraction day and one flexible day for weather, crowds or a slower start. Do not try to cover every gateway town in one trip.",
    sections: [
      { title: "Pick your base town first", body: "The base town controls the trip more than most visitors expect. Start there before buying tickets or making a long list." },
      { title: "Do not cram the whole map", body: "The Smokies are a region, not one compact attraction zone. Treat each day as one main route." },
      { title: "Best simple three-day shape", body: "Day one scenic or park, day two attraction or town, day three flexible food, rain, shopping or missed favorite." },
      { title: "What to book or verify", body: "Verify park rules, closures, road conditions, event dates, attraction hours and any ticketed categories before final plans." },
      { title: "Parking and road reality", body: "Parking and traffic can decide the day. Plan movement before you plan every stop." },
      { title: "Rain backup", body: "Keep an indoor category and food pairing ready. Do not wait until everyone is soaked and hungry." },
      { title: "With kids", body: "Choose one anchor per day and protect rest time." },
      { title: "With seniors", body: "Verify accessibility details and keep walking, parking and seating realistic." },
    ],
    links: related("/plan-your-trip", "/where-to-stay", "/parking-tag", "/rainy-day", "/cades-cove"),
  },
  "/rainy-day": {
    title: "Rainy Day Things to Do in the Smokies",
    description: "Plan a better rainy day in Gatlinburg, Pigeon Forge and the Smokies with indoor ideas, food pairings and traffic-smart backups.",
    directAnswer: "A good Smokies rainy day uses one indoor anchor, nearby food and a short outdoor backup if showers pass. Pigeon Forge is usually easier for family indoor categories. Gatlinburg works well when you can park once and keep the day walkable.",
    sections: [
      { title: "Pigeon Forge rainy-day plan", body: "Choose one indoor attraction category, one meal nearby and one light add-on if the group still has energy." },
      { title: "Gatlinburg rainy-day plan", body: "Park once, use walkable indoor categories and choose food without moving the car repeatedly." },
      { title: "With kids", body: "Kids need one clear anchor and a food reset, not six scattered ideas." },
      { title: "With teens", body: "Arcade, active indoor, food and evening categories can work better than slow browsing." },
      { title: "Low-budget rainy options", body: "Covered shopping, visitor-center-style stops, simple meals and short weather breaks can keep spending down." },
      { title: "Food and dinner-show logic", body: "A rainy day can become food-first or show-category-first if it fits the group. Verify times and terms." },
      { title: "Do not drive all over the county", body: "Heavy rain makes cross-county planning less pleasant and can turn a backup into a grind." },
      { title: "Keep an outdoor backup", body: "If showers pass, add a short overlook, town walk or easy scenic stop." },
      { title: "Sponsored placement policy", body: "Any rainy-day partner placement must be labeled and separated from editorial guidance." },
    ],
    links: related("/plan-your-trip", "/things-to-do/pigeon-forge", "/things-to-do/gatlinburg", "/restaurants", "/deals"),
  },
  "/cades-cove": {
    title: "Cades Cove Smokies Guide",
    description: "Plan a Cades Cove day with timing, crowd caution, Townsend pairing, traffic warnings and source-check reminders.",
    directAnswer: "Cades Cove is best treated as a real park outing, not a quick add-on. Go when you can give the loop enough time, verify current road and vehicle-free schedules, respect wildlife distance and pair the day with Townsend or a simple scenic plan.",
    sections: [
      { title: "Best time to go", body: "Early starts and non-peak periods are usually easier, but verify current schedules and conditions before final plans." },
      { title: "Who should go", body: "Go if your group wants a slower scenic loop, wildlife-viewing possibility, historic structures and a quiet-side park day." },
      { title: "Who should skip or rethink", body: "Rethink it if your group hates slow traffic, has a packed attraction day or expects a quick stop." },
      { title: "How long to allow", body: "Allow a meaningful block of the day. Exact timing varies with traffic, stops, weather and group pace." },
      { title: "Vehicle-free days", body: "Vehicle-free schedules can change by year. Verify the current annual schedule before building around it." },
      { title: "Wildlife respect note", body: "Wildlife is not a photo prop. Keep distance, follow park rules and do not block traffic for unsafe viewing." },
      { title: "What to pair with it", body: "Townsend, Wears Valley, Foothills Parkway or a simple meal pair better than a packed Pigeon Forge list." },
      { title: "Parking and traffic warning", body: "The loop can be slow and pull-offs can be limited. Details can change." },
    ],
    links: [
      { title: "Cades Cove first-time guide", href: "/cades-cove-first-time-guide", description: "Preserved older first-time route." },
      ...related("/scenic-drives", "/where-to-stay", "/accessible-smokies", "/first-time-smokies"),
    ],
  },
  "/accessible-smokies": {
    title: "Accessible Smokies",
    description: "Low-walking and mobility-conscious Smokies planning with scenic drives, overlooks, visitor centers and verification cautions.",
    directAnswer: "Accessibility details change and vary by exact stop. Verify official accessibility information before final plans. For lower-walking days, start with scenic drives, visitor centers, overlooks, easier town plans and meals with realistic parking.",
    sections: [
      { title: "Best low-walking scenic options", body: "Scenic roads and overlooks can reduce walking, but exact surfaces, bathrooms and parking vary." },
      { title: "Scenic drives", body: "Cades Cove, Foothills Parkway, Little River Road, Newfound Gap and other drives can work for lower-walking days when conditions are right." },
      { title: "Visitor centers", body: "Visitor-center-style stops can provide a calmer reset, but verify hours and access before relying on them." },
      { title: "Overlooks", body: "Overlooks can be useful when the group needs views without a trail. Parking can still be limited." },
      { title: "What to avoid if walking is limited", body: "Avoid vague promises like easy, paved or family-friendly unless the exact stop has verified details." },
      { title: "With grandparents", body: "Build shorter blocks with meals, benches, bathrooms and easy exits." },
      { title: "Bathrooms, benches and parking note", body: "These details can make or break the day and should be verified for the exact stop." },
      { title: "Report outdated info", body: "If a page is outdated, use the corrections page so the guide can be updated." },
    ],
    links: related("/plan-your-trip", "/scenic-drives", "/cades-cove", "/restaurants"),
  },
  "/scenic-drives": {
    title: "Best Scenic Drives in the Smokies",
    description: "Choose Smokies scenic drives by base town, crowd tolerance, walking load and current road-condition verification.",
    directAnswer: "The best scenic drive depends on your base and tolerance for slow roads. Cades Cove is a full outing. Roaring Fork is close to Gatlinburg. Foothills Parkway can be calmer from Townsend or Wears Valley. Newfound Gap and NC-side routes require current road-condition checks.",
    sections: [
      { title: "Cades Cove", body: "Best when you can give the loop time and pair it with Townsend or a quiet-side day." },
      { title: "Roaring Fork", body: "Useful from Gatlinburg when the route is open and your group can handle narrow, slow road pacing." },
      { title: "Foothills Parkway", body: "Good for views with less walking and a Townsend or Wears Valley frame." },
      { title: "Newfound Gap", body: "A major cross-mountain route that needs current road and weather checks." },
      { title: "Little River Road", body: "A useful scenic connector when it fits the route and current conditions." },
      { title: "NC-side drives", body: "Strong for Cherokee, Bryson City and Deep Creek-style trips. Verify cross-mountain impacts before routing." },
      { title: "Best for low walking", body: "Foothills Parkway, overlooks and visitor-center-style stops can work, with access details verified." },
      { title: "Best for first-timers", body: "Pick one drive that matches your base instead of trying to sample every road." },
      { title: "Best if you hate crowds", body: "Avoid peak windows and choose quieter-side routes when possible." },
      { title: "Road closure verification note", body: sourceLine },
    ],
    links: related("/plan-your-trip", "/cades-cove", "/accessible-smokies", "/first-time-smokies"),
  },
  "/hiking": {
    title: "Smoky Mountains Hiking Guide for Realistic Trip Planning",
    description: "Plan Smokies hikes by parking reality, closure checks, family fit, waterfalls, views and cautious accessibility language.",
    directAnswer: "Pick Smokies hikes by parking, group ability, weather and current closures before scenery. Easy, paved or family-friendly does not automatically mean stroller-friendly or wheelchair-suitable. Verify official trail and closure information before you go.",
    sections: [
      { title: "Easy hikes", body: "Easy is relative. Match distance, grade, surface and parking to your actual group." },
      { title: "Waterfalls", body: "Waterfall routes are popular and can be affected by closures, crowding and slippery conditions." },
      { title: "Family-friendly", body: "Family-friendly should mean the group can finish without forcing it. Check walking load and bathrooms." },
      { title: "Big views", body: "Some big views require longer drives or higher-elevation weather checks." },
      { title: "Parking fills early", body: "Popular trail parking can fill during busy periods. Verify current guidance before relying on a trailhead." },
      { title: "Closure verification note", body: sourceLine },
      { title: "What paved does not always mean", body: "Paved does not automatically mean flat, stroller-simple or wheelchair-suitable." },
      { title: "Official current conditions", body: "Use official park current-condition resources before final hiking plans." },
    ],
    links: related("/plan-your-trip", "/parking-tag", "/scenic-drives", "/accessible-smokies"),
  },
  "/things-to-do": {
    title: "Things to Do in the Smokies",
    description: "Match Smokies activities to kids, teens, rain, budget, scenery, low walking, couples and the right gateway town.",
    directAnswer: "The best thing to do in the Smokies depends on your group and route. Families often need Pigeon Forge categories. Walkable downtown plans fit Gatlinburg. Scenic and lower-walking days fit park roads and overlooks. Rainy days need one indoor anchor and nearby food.",
    sections: [
      { title: "Best with kids", body: "Use one anchor attraction or scenic stop, then food and rest. Do not stack every kid-friendly category." },
      { title: "Best with teens", body: "Active indoor, thrill, food and evening categories can work well when the route is tight." },
      { title: "Best rainy-day picks", body: "Choose indoor categories by town and keep food nearby." },
      { title: "Best free or cheap", body: "Scenic drives, overlooks, visitor-center-style stops and town walks can protect the budget." },
      { title: "Best scenic", body: "Cades Cove, Foothills Parkway, Newfound Gap and other drives work best when matched to the base town." },
      { title: "Best low-walking", body: "Scenic drives, overlooks and seated categories can help, but verify exact access." },
      { title: "Best for couples", body: "Townsend, Wears Valley, scenic drives, food-first routes and quieter evenings usually beat a packed list." },
      { title: "Gatlinburg", body: "Use walkability, park access, downtown food and indoor categories." },
      { title: "Pigeon Forge", body: "Use Parkway attraction categories, Dollywood, dinner shows, arcades and family stops with route discipline." },
      { title: "Sevierville", body: "Use value, outlets, gateway access and local business pacing." },
      { title: "Townsend", body: "Use quiet-side scenic drives, Cades Cove and slower park days." },
    ],
    links: related("/plan-your-trip", "/things-to-do/gatlinburg", "/things-to-do/pigeon-forge", "/rainy-day", "/deals"),
  },
  "/things-to-do/gatlinburg": {
    title: "Things to Do in Gatlinburg",
    description: "Plan Gatlinburg by walkability, park access, rainy-day categories, food nearby, kids and parking reality.",
    directAnswer: "Gatlinburg works best when you park once, keep the plan walkable and pair downtown stops with food or park access. It is not the easiest fit for visitors who hate crowds or want wide, simple parking at every stop.",
    sections: [
      { title: "Walkable downtown logic", body: "Use the Parkway and nearby walkable areas as one route instead of moving the car for each stop." },
      { title: "Park access", body: "Gatlinburg is a strong TN-side park gateway, but verify current road and parking conditions." },
      { title: "Rainy-day options by category", body: "Indoor attractions, food, shopping and covered pauses can work when grouped tightly." },
      { title: "Food nearby", body: "Choose meals near the walking route or lodging." },
      { title: "Best with kids", body: "Pick one downtown anchor and keep the rest flexible." },
      { title: "Skip if", body: "Skip a Gatlinburg-heavy day if your group hates tight streets, walking or peak downtown crowds." },
      { title: "Parking note", body: "Park once if you can. Moving repeatedly can waste the day." },
    ],
    links: related("/restaurants/gatlinburg", "/gatlinburg-vs-pigeon-forge", "/rainy-day", "/plan-your-trip"),
  },
  "/things-to-do/pigeon-forge": {
    title: "Things to Do in Pigeon Forge",
    description: "Plan Pigeon Forge by Parkway corridor, Dollywood category, dinner shows, rainy-day options and family fit.",
    directAnswer: "Pigeon Forge is strongest for families, Dollywood, dinner shows and attraction categories along the Parkway. The better move is choosing one corridor plan, not stacking the whole strip into a single day.",
    sections: [
      { title: "Parkway corridor logic", body: "Group stops by corridor and meal area so the Parkway does not become the day." },
      { title: "Dollywood category", body: "Treat Dollywood as a main event and verify current park details before you go." },
      { title: "Dinner shows category", body: "Dinner-show nights can anchor an evening, but verify schedules, terms and fit." },
      { title: "Rainy-day options", body: "Pigeon Forge has strong indoor categories. Pick one anchor and food nearby." },
      { title: "Mini golf, arcades and go-karts", body: "Use these as categories without assuming every specific business fits every group." },
      { title: "Best with kids", body: "Families usually do better with one anchor, one meal and one lighter add-on." },
      { title: "Skip if", body: "Skip a Pigeon Forge-heavy plan if your group wants quiet mountain town pacing or walk-everywhere simplicity." },
    ],
    links: related("/restaurants/pigeon-forge", "/pigeon-forge-with-kids", "/rainy-day", "/plan-your-trip"),
  },
  "/restaurants": {
    title: "Smokies Restaurants by Situation",
    description: "Choose Smokies restaurants by route, town, family needs, rainy days, budget and timing instead of chasing ratings across town.",
    directAnswer: "Choose Smokies food by the route you are already using. A good restaurant pick can become a bad plan if it sends you across Gatlinburg, Pigeon Forge or the county at the wrong time. Start with town, meal type and parking reality.",
    sections: [
      { title: "Breakfast and pancakes", body: "Breakfast is a useful anchor, especially in Gatlinburg, but lines and parking still matter." },
      { title: "BBQ", body: "BBQ works best when it sits near the route, not as a far detour." },
      { title: "Family-friendly", body: "Choose speed, seating, noise tolerance and nearby plans before chasing a long list." },
      { title: "Date night", body: "Pick by town and evening plan so the drive does not flatten the mood." },
      { title: "Budget eats", body: "Budget food helps only if the parking, timing and route still work." },
      { title: "Near Dollywood", body: "After a park day, keep food close and simple unless the group has real energy left." },
      { title: "After Cades Cove", body: "Townsend or Wears Valley often makes more sense than a late cross-county meal." },
      { title: "Rainy-day meals", body: "Use food as the reset between indoor categories." },
      { title: "Local note", body: "Choose food by route, not just rating." },
      { title: "Business listing status note", body: "Listings and partner placements will be labeled when verified or sponsored." },
    ],
    links: related("/restaurants/gatlinburg", "/restaurants/pigeon-forge", "/deals", "/plan-your-trip"),
  },
  "/restaurants/gatlinburg": {
    title: "Gatlinburg Restaurants by Situation",
    description: "Choose Gatlinburg restaurants for walkable meals, breakfast, family food, date night and after-park timing.",
    directAnswer: "Gatlinburg food works best when it fits a walkable downtown or park-access plan. Choose the meal by where you already parked, what the group can walk and whether the day needs a quick reset or a slower evening.",
    sections: [
      { title: "Best for walkable meals", body: "Stay near the route you are already walking." },
      { title: "Breakfast and pancakes category", body: "Breakfast can be a useful anchor, but verify hours and expect peak demand." },
      { title: "Family meals", body: "Choose simple access and group tolerance before chasing a name." },
      { title: "Date night", body: "Keep the evening walkable or close to lodging." },
      { title: "After park day", body: "After a park day, choose a meal that does not require another hard parking plan." },
      { title: "Parking and walking note", body: "Park once where possible and verify accessibility needs." },
      { title: "Claim or update listing", body: "Businesses can request updates through the corrections or advertise path." },
    ],
    links: related("/restaurants", "/things-to-do/gatlinburg", "/gatlinburg-vs-pigeon-forge", "/plan-your-trip"),
  },
  "/restaurants/pigeon-forge": {
    title: "Pigeon Forge Restaurants by Situation",
    description: "Choose Pigeon Forge restaurants for families, Dollywood days, dinner-show nights, BBQ, breakfast and Parkway traffic reality.",
    directAnswer: "Pigeon Forge restaurants work best when they stay near your Parkway corridor, lodging or Dollywood route. Do not cross the whole strip for a meal unless it is worth the traffic and timing for your group.",
    sections: [
      { title: "Best for families", body: "Families need seating, speed, parking and a route that does not create another meltdown window." },
      { title: "After Dollywood", body: "Keep the meal close unless everyone still has energy." },
      { title: "Dinner-show nights", body: "A dinner show can be the evening plan, not an add-on after an overloaded day." },
      { title: "BBQ", body: "Use BBQ as a route fit, not a far detour." },
      { title: "Breakfast", body: "Breakfast can anchor a day, but verify hours and peak waits." },
      { title: "Parkway traffic note", body: "The Parkway can make short distances feel long during peak times." },
      { title: "Claim or update listing", body: "Businesses can request updates through the corrections or advertise path." },
    ],
    links: related("/restaurants", "/things-to-do/pigeon-forge", "/rainy-day", "/plan-your-trip"),
  },
  "/deals": {
    title: "Smokies Deals That Fit the Trip",
    description: "Use Smokies deals wisely without chasing coupons across town or letting discounts choose the wrong day for your group.",
    directAnswer: "Smokies deals are useful when they fit the trip. They are a bad guide when they make you chase coupons across town. There are no verified public deals listed here yet, and future offers should show terms, expiration and sponsor status clearly.",
    sections: [
      { title: "No verified deals listed yet", body: "No active verified public deals are listed on this page right now." },
      { title: "How to use deals wisely", body: "Start with the plan, then use a deal if it fits the route, group and timing." },
      { title: "Deal categories coming later", body: "Restaurants, attractions, shows, lodging and rainy-day categories can be useful after verification." },
      { title: "Restaurants", body: "Restaurant deals should show terms and fit the meal route." },
      { title: "Attractions", body: "Attraction deals should not cause visitors to stack too many paid stops." },
      { title: "Shows", body: "Show offers need schedule and terms verification." },
      { title: "Lodging", body: "Lodging offers need clear dates and terms before publication." },
      { title: "Rainy-day", body: "Rainy-day deals should be useful only when they fit the backup plan." },
      { title: "Submit a deal", body: "Future business submissions should include terms, expiration and sponsor status." },
      { title: "Report expired deal", body: "Visitors and businesses should report expired or unclear offers." },
      { title: "Sponsored disclosure note", body: "Paid deal placement must be labeled and must not override best-fit planning guidance." },
    ],
    links: related("/plan-your-trip", "/restaurants", "/things-to-do", "/rainy-day"),
  },
  "/advertise": {
    title: "Advertise With Smokies Insider Guide",
    description: "Join the future Smokies Insider Guide partner interest list for clearly labeled planning-stage visibility.",
    directAnswer: "Smokies Insider Guide is being built as a free planning resource first. Local businesses can join the future partner interest list, but businesses can buy visibility, not editorial truth. No traffic claims or rate card are published yet.",
    sections: [
      { title: "Current status", body: "Smokies Insider Guide is being built as a free planning resource for visitors." },
      { title: "Founding partner interest list", body: "Local businesses can express interest in future clearly labeled placements." },
      { title: "Featured listing", body: "Future listing visibility may be available after verification and labeling." },
      { title: "Sponsored guide placement", body: "Sponsored placements must be labeled and relevant to the page." },
      { title: "Deal placement", body: "Future deal placements must include terms, expiration and sponsor status." },
      { title: "Newsletter sponsorship", body: "Future newsletter placements should be clearly labeled." },
      { title: "Itinerary sponsor", body: "Future itinerary sponsor slots must remain separated from best-fit guidance." },
      { title: "Trust rule", body: "Businesses can buy visibility, not editorial truth." },
      { title: "Inquiry CTA", body: "Use the contact path to ask about the future partner list." },
    ],
    links: [
      { title: "Sponsored content policy", href: "/sponsored-content-policy", description: "How labels and paid placements work." },
      { title: "Editorial policy", href: "/editorial-policy", description: "Visitor-first rules." },
      { title: "Corrections", href: "/corrections", description: "Report outdated information." },
    ],
  },
  "/what-to-skip": {
    title: "What to Skip in the Smokies When Time Is Tight",
    description: "Avoid Smokies planning mistakes without attacking local businesses: bad routing, overstacked paid stops, parking gaps and coupon-chasing.",
    directAnswer: "When time is tight, skip plans that create more driving than value. Do not drive across the county for one small stop, stack too many paid attractions, treat Cades Cove as a quick add-on or build a day around unknown parking.",
    sections: [
      { title: "Skip driving across the county for one small stop", body: "One far stop can wreck the rest of the day." },
      { title: "Skip stacking too many paid attractions", body: "Paid stops are better when they are chosen, not piled up." },
      { title: "Skip downtown Gatlinburg at peak times if you hate crowds", body: "Gatlinburg can be great, but it is not magic for crowd-averse groups." },
      { title: "Skip Cades Cove as a quick add-on", body: "Cades Cove needs time and patience." },
      { title: "Skip unknown parking plans", body: "Parking uncertainty can undo an otherwise good route." },
      { title: "Skip coupon-chasing across town", body: "A discount that sends you to the wrong place is not a savings." },
      { title: "Better moves", body: "Choose one base, one anchor, nearby food and a backup that fits the same route." },
    ],
    links: related("/plan-your-trip", "/where-to-stay", "/deals", "/rainy-day", "/cades-cove"),
  },
};
